/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Task } from "./components/task-tracker/task-tracker";
export namespace Components {
    interface AddTaskModal {
        "onAdd": (task: any) => void;
    }
    interface MyButton {
        "color": string;
        "text": string;
    }
    interface MyTask {
        "onDelete": (id: number) => void;
        "onToggle": (id: number) => void;
        "task": Task;
    }
    interface MyTasks {
        "onDelete": (id: number) => void;
        "onToggle": (id: number) => void;
        "tasks": Task[];
    }
    interface TaskTracker {
    }
}
declare global {
    interface HTMLAddTaskModalElement extends Components.AddTaskModal, HTMLStencilElement {
    }
    var HTMLAddTaskModalElement: {
        prototype: HTMLAddTaskModalElement;
        new (): HTMLAddTaskModalElement;
    };
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLMyTaskElement extends Components.MyTask, HTMLStencilElement {
    }
    var HTMLMyTaskElement: {
        prototype: HTMLMyTaskElement;
        new (): HTMLMyTaskElement;
    };
    interface HTMLMyTasksElement extends Components.MyTasks, HTMLStencilElement {
    }
    var HTMLMyTasksElement: {
        prototype: HTMLMyTasksElement;
        new (): HTMLMyTasksElement;
    };
    interface HTMLTaskTrackerElement extends Components.TaskTracker, HTMLStencilElement {
    }
    var HTMLTaskTrackerElement: {
        prototype: HTMLTaskTrackerElement;
        new (): HTMLTaskTrackerElement;
    };
    interface HTMLElementTagNameMap {
        "add-task-modal": HTMLAddTaskModalElement;
        "my-button": HTMLMyButtonElement;
        "my-task": HTMLMyTaskElement;
        "my-tasks": HTMLMyTasksElement;
        "task-tracker": HTMLTaskTrackerElement;
    }
}
declare namespace LocalJSX {
    interface AddTaskModal {
        "onAdd"?: (task: any) => void;
    }
    interface MyButton {
        "color"?: string;
        "onOnClick"?: (event: CustomEvent<any>) => void;
        "text"?: string;
    }
    interface MyTask {
        "onDelete"?: (id: number) => void;
        "onToggle"?: (id: number) => void;
        "task"?: Task;
    }
    interface MyTasks {
        "onDelete"?: (id: number) => void;
        "onToggle"?: (id: number) => void;
        "tasks"?: Task[];
    }
    interface TaskTracker {
    }
    interface IntrinsicElements {
        "add-task-modal": AddTaskModal;
        "my-button": MyButton;
        "my-task": MyTask;
        "my-tasks": MyTasks;
        "task-tracker": TaskTracker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-task-modal": LocalJSX.AddTaskModal & JSXBase.HTMLAttributes<HTMLAddTaskModalElement>;
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            "my-task": LocalJSX.MyTask & JSXBase.HTMLAttributes<HTMLMyTaskElement>;
            "my-tasks": LocalJSX.MyTasks & JSXBase.HTMLAttributes<HTMLMyTasksElement>;
            "task-tracker": LocalJSX.TaskTracker & JSXBase.HTMLAttributes<HTMLTaskTrackerElement>;
        }
    }
}
